version: '2.2'

services:
  postgres:
    restart: always
    image: "postgres:9.6"
    ports:
    - "5432"
    environment:
      POSTGRES_DB: thingsboard
    volumes:
      - ./tb-node/postgres:/var/lib/postgresql/data
  tb1:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - kafka
      - redis
      - postgres
  tb2:
    env_file:
      - tb-node.postgres.env
    depends_on:
      - kafka
      - redis
      - postgres
