version: '2.2'

services:
  postgres:
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
  tb1:
    volumes:
      - tb-log-volume:/var/log/thingsboard
  tb2:
    volumes:
      - tb-log-volume:/var/log/thingsboard

volumes:
  postgres-db-volume:
    external: true
    name: ${POSTGRES_DATA_VOLUME}
  tb-log-volume:
    external: true
    name: ${TB_LOG_VOLUME}
