version: '2.2'

services:
  cassandra:
    restart: always
    image: "cassandra:3.11.3"
    ports:
    - "9042"
    volumes:
      - ./tb-node/cassandra:/var/lib/cassandra
  tb1:
    env_file:
      - tb-node.cassandra.env
    depends_on:
      - kafka
      - redis
      - cassandra
  tb2:
    env_file:
      - tb-node.cassandra.env
    depends_on:
      - kafka
      - redis
      - cassandra
